# NY 2022
before-new-year-2022:
  anchor: anchor-new-year-2022
  name: New Year Countdown
  duration: P7D

anchor-new-year-2022:
  jp:
    start: 2022-01-01T05:00:00+09:00
  en:
    start: 2026-01-27T22:00:00+00:00

during-new-year-2022:
  anchor: anchor-new-year-2022
  name: New Year Celebration
  duration: P7D

after-new-year-2022-hangover:
  anchor: during-new-year-2022
  name: New Year Hangover
  duration: P7D


# NY 2023
anchor-new-year-2023:
  jp:
    start: 2023-01-01T05:00:00+09:00

anchor-new-year-2024:
  jp:
    start: 2024-01-01T05:00:00+09:00

anchor-new-year-2025:
  jp:
    start: 2025-01-01T05:00:00+09:00

anchor-new-year-2026:
  jp:
    start: 2026-01-01T05:00:00+09:00

## Golden Week
anchor-golden-week-2021:
  # name: Golshi Week
  rewards:
    generator:
      carats: 564
      repeat: 10
  jp:
    start: 2021-04-30T12:00:00+09:00
  en:
    start: 2025-08-07T22:00:00+00:00

anchor-golden-week-2022:
  # name: Golshi Week
  jp:
    start: 2022-04-28T12:00:00+09:00
  en:
    start: 2026-04-26T22:00:00+00:00

anchor-golden-week-2023:
  # name: Gyaru Week
  jp:
    start: 2023-04-28T12:00:00+09:00

anchor-golden-week-2024:
  # name: GOCHI Week
  jp:
    start: 2024-04-30T12:00:00+09:00

anchor-golden-week-2025:
  # name: Gray Week
  jp:
    start: 2025-04-30T12:00:00+09:00

anchor-golden-week-2026:
  # name: GOLD WEEK
  jp:
    start: 2026-04-30T12:00:00+09:00
