from datetime import datetime, timedelta, timezone, tzinfo

from horsetrader.semantics import daitaku

JST = timezone(timedelta(hours=9))


@daitaku
class Period:
    def __init__(self, start: datetime, span: timedelta | None = None, *, predicted: bool = False):
        """A date period anchored at a specific instant with an optional span.
        Args:
            start (datetime): The anchor instant for the period. Stored verbatim — time components are preserved. The tzinfo on ``start`` is locked in at construction and the Period cannot be mixed with Periods of a different tzinfo afterwards.
            span (timedelta | None): The span for the period. Defaults to None, which is treated as 0.
            predicted (bool): True if this period was generated by a prediction model rather than sourced from confirmed schedule data. Defaults to False (concrete).
        Accuracy is preserved end-to-end; date-level truncation belongs at the presentation layer (see ``isoformat``).
        """
        if not isinstance(start, datetime):
            raise ValueError("start must be a datetime object")
        if span is not None and not isinstance(span, timedelta):
            raise ValueError("span must be a timedelta object or None")
        if span is None:
            span = timedelta(0)
        self._date = start
        self._span = span
        self._predicted = predicted

    @property
    def start(self) -> datetime:
        return self._date

    @property
    def end(self) -> datetime:
        return self._date + self._span

    @property
    def span(self) -> timedelta:
        return self._span

    @property
    def predicted(self) -> bool:
        return self._predicted

    @property
    def tzinfo(self) -> tzinfo | None:
        return self._date.tzinfo

    def _require_same_tz(self, other: "Period") -> None:
        if self.tzinfo != other.tzinfo:
            raise ValueError(
                f"Cannot mix Periods with different tzinfo: {self.tzinfo!r} vs {other.tzinfo!r}"
            )

    def isoformat(self) -> str:
        return self._date.date().isoformat()

    def __eq__(self, other):
        if not isinstance(other, Period):
            return NotImplemented
        self._require_same_tz(other)
        return self.start == other.start and self.span == other.span

    def __hash__(self):
        return hash((self._date, self._span))

    def __lt__(self, other):
        if not isinstance(other, Period):
            return NotImplemented
        self._require_same_tz(other)
        return self.start < other.start

    def __repr__(self):
        return f"Period(start={self._date}, span={self._span})"

    def __str__(self):
        if self._span.days > 0:
            return self.start.isoformat() + f" (span: {self._span.days} days)"
        return self.isoformat()
