from collections.abc import Iterable
from datetime import datetime, timedelta, timezone, tzinfo
from typing import SupportsIndex

from horsetrader.semantics import daitaku

JST = timezone(timedelta(hours=9))


@daitaku
class Period:
    def __init__(self, start: datetime, span: timedelta | None = None, *, predicted: bool = False):
        """A date period anchored at a specific instant with an optional span.
        Args:
            start (datetime): The anchor instant for the period. Stored verbatim — time components are preserved. The tzinfo on ``start`` is locked in at construction and the Period cannot be mixed with Periods of a different tzinfo afterwards.
            span (timedelta | None): The span for the period. Defaults to None, which is treated as 0.
            predicted (bool): True if this period was generated by a prediction model rather than sourced from confirmed schedule data. Defaults to False (concrete).
        Accuracy is preserved end-to-end; date-level truncation belongs at the presentation layer (see ``isoformat``).
        """
        if not isinstance(start, datetime):
            raise ValueError("start must be a datetime object")
        if span is not None and not isinstance(span, timedelta):
            raise ValueError("span must be a timedelta object or None")
        if span is None:
            span = timedelta(0)
        self._date = start
        self._span = span
        self._predicted = predicted

    @property
    def start(self) -> datetime:
        return self._date

    @property
    def end(self) -> datetime:
        return self._date + self._span

    @property
    def span(self) -> timedelta:
        return self._span

    @property
    def predicted(self) -> bool:
        return self._predicted

    @property
    def tzinfo(self) -> tzinfo | None:
        return self._date.tzinfo

    def _require_same_tz(self, other: "Period") -> None:
        if self.tzinfo != other.tzinfo:
            raise ValueError(
                f"Cannot mix Periods with different tzinfo: {self.tzinfo!r} vs {other.tzinfo!r}"
            )

    def isoformat(self) -> str:
        return self._date.date().isoformat()

    def __eq__(self, other):
        if not isinstance(other, Period):
            return NotImplemented
        self._require_same_tz(other)
        return self.start == other.start and self.span == other.span

    def __hash__(self):
        return hash((self._date, self._span))

    def __lt__(self, other):
        if not isinstance(other, Period):
            return NotImplemented
        self._require_same_tz(other)
        return self.start < other.start

    def __repr__(self):
        predicted = f", predicted={self._predicted}" if self._predicted else ""
        return f"Period(start={self._date}, span={self._span}{predicted})"

    def __str__(self):
        predicted = " [predicted]" if self._predicted else ""
        if self._span.days > 0:
            return self.start.isoformat() + f" (span: {self._span.days} days){predicted}"
        return self.isoformat() + predicted


@daitaku
class Periods(list[Period]):
    """A list of Periods with at most one Period per tzinfo.

    Enforced on every mutation (append, extend, insert) — adding a second
    Period whose tzinfo already exists raises ValueError. Reads stay plain
    list semantics, so callers can iterate as normal and use
    ``next(p for p in periods if p.tzinfo == tz)`` instead of ``min(...)``.
    """

    def __init__(self, periods: Iterable[Period] | None = None) -> None:
        super().__init__()
        if periods is not None:
            self.extend(periods)

    def _reject_duplicate(self, period: Period) -> None:
        if any(p.tzinfo == period.tzinfo for p in self):
            raise ValueError(
                f"Periods already contains a Period with tzinfo {period.tzinfo!r}"
            )

    def append(self, period: Period) -> None:
        self._reject_duplicate(period)
        super().append(period)

    def extend(self, periods: Iterable[Period]) -> None:
        new = list(periods)
        seen: set[tzinfo | None] = {p.tzinfo for p in self}
        for p in new:
            if p.tzinfo in seen:
                raise ValueError(
                    f"Periods already contains a Period with tzinfo {p.tzinfo!r}"
                )
            seen.add(p.tzinfo)
        super().extend(new)

    def insert(self, index: SupportsIndex, period: Period) -> None:
        self._reject_duplicate(period)
        super().insert(index, period)
