#!/usr/bin/env python3
"""Generate the checked-in Umamusume client database table catalog."""

from __future__ import annotations

import argparse
import hashlib
import sqlite3
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATABASE = ROOT / ".cache/databases/global/master.mdb"
DEFAULT_OUTPUT = ROOT / "docs/database/catalog.md"

# Ordered from narrowest to broadest where prefixes overlap.
FAMILIES = (
    ("Single-player training", ("single_mode_",)),
    ("Team Building", ("team_building_",)),
    ("Team Stadium", ("team_stadium_",)),
    ("Story events", ("story_event_",)),
    ("Main story", ("main_story_",)),
    ("Legend Races", ("legend_race",)),
    ("Daily Races", ("daily_race",)),
    ("Champions Meeting", ("champions_",)),
    ("League of Heroes", ("heroes_",)),
    ("Collection raids", ("collect_", "fan_raid_")),
    ("Map events", ("map_event_",)),
    ("Characters and cards", ("chara_", "character_", "card_", "mob_")),
    ("Support cards", ("support_card_",)),
    ("Skills", ("skill_", "available_skill_")),
    ("Races", ("race",)),
    ("Gacha", ("gacha_",)),
    ("Campaigns", ("campaign_",)),
    ("Home", ("home_", "homestory_")),
    ("Stories", ("story_", "short_episode")),
    ("Audio and live", ("audio_", "live_", "jukebox_")),
    ("Items and exchanges", ("item_", "limited_exchange", "piece_data")),
    ("Training presentation", ("training_", "training_cutt_", "transfer_")),
    ("Inheritance", ("succession_",)),
    ("Missions", ("mission_",)),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--database",
        type=Path,
        default=DEFAULT_DATABASE,
        help="master.mdb to inspect",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Markdown file to generate",
    )
    return parser.parse_args()


def quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def md5(path: Path) -> str:
    digest = hashlib.md5()  # noqa: S324 - cache identity, not security
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def family_for(table: str) -> str:
    for family, prefixes in FAMILIES:
        if table.startswith(prefixes):
            return family
    return "Other"


def render(database: Path) -> str:
    database = database.resolve()
    if not database.is_file():
        raise FileNotFoundError(database)

    connection = sqlite3.connect(f"{database.as_uri()}?mode=ro", uri=True)
    try:
        connection.execute("PRAGMA query_only = ON")
        quick_check = connection.execute("PRAGMA quick_check").fetchone()[0]
        objects = dict(
            connection.execute(
                """
                SELECT type, count(*)
                  FROM sqlite_master
                 WHERE name NOT LIKE 'sqlite_%'
              GROUP BY type
                """
            )
        )
        tables = [
            row[0]
            for row in connection.execute(
                """
                SELECT name
                  FROM sqlite_master
                 WHERE type = 'table'
                   AND name NOT LIKE 'sqlite_%'
              ORDER BY name
                """
            )
        ]

        families: dict[str, list[tuple[str, int, int, str, int]]] = defaultdict(list)
        declared_foreign_keys = 0
        for table in tables:
            quoted = quote_identifier(table)
            row_count = connection.execute(f"SELECT count(*) FROM {quoted}").fetchone()[0]
            columns = connection.execute(f"PRAGMA table_info({quoted})").fetchall()
            primary_key = ", ".join(
                column[1]
                for column in sorted(columns, key=lambda column: column[5])
                if column[5]
            )
            index_count = connection.execute(
                "SELECT count(*) FROM sqlite_master WHERE type = 'index' AND tbl_name = ?",
                (table,),
            ).fetchone()[0]
            declared_foreign_keys += len(
                connection.execute(f"PRAGMA foreign_key_list({quoted})").fetchall()
            )
            families[family_for(table)].append(
                (table, row_count, len(columns), primary_key or "-", index_count)
            )
    finally:
        connection.close()

    lines = [
        "# Global `master.mdb` table catalog",
        "",
        "Generated by `venv/bin/python scripts/document_client_database.py` from",
        "the cached installed-client database. Regenerate it whenever the source",
        "MD5 changes; do not hand-edit this file.",
        "",
        "| Snapshot property | Value |",
        "| --- | ---: |",
        f"| MD5 | `{md5(database)}` |",
        f"| Bytes | {database.stat().st_size:,} |",
        f"| Tables | {objects.get('table', 0):,} |",
        f"| Indexes | {objects.get('index', 0):,} |",
        f"| Declared foreign keys | {declared_foreign_keys:,} |",
        f"| `PRAGMA quick_check` | `{quick_check}` |",
        "",
        "The family headings are documentation conveniences inferred from table",
        "names, not namespaces declared by SQLite. Row counts and physical schema",
        "facts are exact for the identified snapshot. A matching column name does",
        "not establish a relationship; the client database declares no foreign keys.",
        "",
    ]

    family_order = [family for family, _ in FAMILIES] + ["Other"]
    for family in family_order:
        entries = families.get(family)
        if not entries:
            continue
        lines.extend(
            (
                f"## {family}",
                "",
                "| Table | Rows | Columns | Primary key | Indexes |",
                "| --- | ---: | ---: | --- | ---: |",
            )
        )
        for table, rows, columns, primary_key, indexes in entries:
            lines.append(
                f"| `{table}` | {rows:,} | {columns} | `{primary_key}` | {indexes} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(args.database), encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
