anchor-anni-0_5: # NOQA
  en:
    start: 2025-11-03T22:00:00+00:00 # Unity Cup
  jp:
    start: 2021-08-24T12:00:00+09:00 # Aoharu Hai - started on 2021-08-30, anni was earlier
anchor-anni-1_0:
  en:
    start: 2026-03-12T22:00:00+00:00 # Trackblazer
  jp:
    start: 2022-02-24T12:00:00+09:00 # Make a New Track

# 1.5th Anniversary
anchor-anni-1_5:
  jp:
    start: 2022-08-24T12:00:00+09:00 # Grand Live
during-anni-1_5: # Part 2
  anchor: anchor-anni-1_5
  name: 1.5th Anniversary Celebration Part 2
  duration: P28D
  rewards:
    free_carats: 3000
    sequence:
      type: free_carats
      sequence: [150,150,Null,150,150,150,150,150,Null,150,150,150]
after-anni-1_5p2: # Part 3 starts 9/2
  anchor: during-anni-1_5
  name: 1.5th Anniversary Celebration Part 3
  duration: P28D

anchor-anni-2_0:
  jp:
    start: 2023-02-24T12:00:00+09:00 # Grand Masters
anchor-anni-2_5:
  jp:
    start: 2023-08-24T12:00:00+09:00 # Project L'Arc
anchor-anni-3_0:
  jp:
    start: 2024-02-24T12:00:00+09:00 # U.A.F. Ready GO!
anchor-anni-3_5:
  jp:
    start: 2024-08-24T12:00:00+09:00
anchor-anni-4_0:
  jp:
    start: 2025-02-24T12:00:00+09:00 # The Twinkle Legends
anchor-anni-4_5:
  jp:
    start: 2025-08-24T12:00:00+09:00
anchor-anni-5_0:
  jp:
    start: 2026-02-24T12:00:00+09:00 # Beyond Dreams
